config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :locations,         only: [:index, :show]
  resources :favorites,         only: [:index, :create]
  resources :api,              only: [:index]
  get 'auth/twitter',                                   as: :login
  get 'auth/twitter/callback',  to: 'sessions#create'
  get 'logout',                 to: 'sessions#destroy', as: :logout
  get 'profile',                to: 'users#show'
  get 'search',                 to: "search#index"
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  has_many :user_favorites
  has_many :users, through: :user_favorites

  def self.find_or_create_fave(api_id, category, name, image_url, address)
    favorite = Favorite.find_or_create_by(api_id: api_id)
    image = Location.yelp_image_name(image_url)
    favorite.update_attribute(:category, category)
    favorite.update_attribute(:name, name)
    favorite.update_attribute(:image_url, image_url)
    favorite.update_attribute(:address, address)
    favorite
  end

end

app/models/location.rb
class Location

  def self.find_locations(categories, address, distance)
    locations = {}
    address = Location.default_addess(address)
    distance_in_meters = Location.miles_to_meters(distance)
    categories.each do |category|
      if category == "events"
        locations[:Event] = EventbriteService.new.find_event(address, distance)
      else
        readable_category = category.split("_").map(&:capitalize).join(" ").singularize
        locations[readable_category] = YelpService.new.find_location(category, address, distance_in_meters)
      end
    end
    locations
  end

  def self.location_details(id)
    YelpService.new.location_details(id)
  end

  def self.yelp_image_name(image_url)
    if image_url
      image_url.gsub('/ms.jpg', '/o.jpg')
    else
      "http://s3-media4.fl.yelpcdn.com/assets/srv0/yelp_styleguide/c73d296de521/assets/img/default_avatars/business_90_square.png"
    end
  end

  def self.address(location)
    location.location.display_address.first
  end

  def self.default_addess(address)
    # coordinates = { latitude: 37.7577, longitude: -122.4376 }
    if address == ""
      address = 'Denver'
    end
    address
  end

  def self.miles_to_meters(distance)
    distance = distance.to_i / 0.00062137
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_favorites
  has_many :favorites, through: :user_favorites

  def self.find_or_create_from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.screen_name        = auth_info.extra.raw_info.screen_name
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end
end

app/models/user_favorite.rb
class UserFavorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorite

  def self.add_to_faves(user, favorite)
    UserFavorite.create(user_id: user.id, favorite_id: favorite.id)
  end


end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  respond_to :json

  def index
    if params[:location_categories]
      @locations = Location.find_locations(params[:location_categories], params[:address], params[:distance])
      respond_with @locations
    else
      flash[:error] = "You must choose at least one category."
      redirect_to search_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_current_user
    render file: "/public/403" unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_current_user

  def create
    @api_id = params[:id]
    @category = params[:category]
    favorite = Favorite.find_or_create_fave(params[:id], params[:category], params[:name], params[:image_url], params[:address])
    UserFavorite.add_to_faves(current_user, favorite)
    @favorites = current_user.favorites
    redirect_to profile_path
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :require_current_user

  def index
    @address = params[:address]
    @locations = []
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.find_or_create_from_omniauth(auth_info)
      session[:user_id] = user.id
      redirect_to search_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private

    def auth_info
      request.env["omniauth.auth"]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_current_user

  def show
    @favorites = current_user.favorites
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/yelp_controller.rb
class YelpController < ApplicationController
  respond_to :json

  def index
    if params[:location_categories]
      render json: Location.find_locations(params[:location_categories], params[:address], params[:distance])
    else
      flash[:error] = "You must choose at least one category."
      redirect_to search_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Find Your Night</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <%= render "shared/nav" %>

  <% flash.each do |type, msg| %>
    <%= content_tag :div, msg.html_safe %>
  <% end %>

  <%= yield %>

  <%#= render "shared/footer" %>
</div>

  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/locations/_event_card.html.erb
  <!-- '<div class="event-card"><img src='
  + location["logo"]["url"]
  + '<div class="caption"><h5>Event:</h5><h4>'
  +  response["name"]["text"]
  + '</h4><p><a href="/'
  + response["id"]
  + '?category=Event'
  + '" class = "btn btn-primary btn-xs"></div></div>' -->

app/views/locations/_event_detail_card.html.erb
<!-- <h2><%= @location["name"]["text"] %></h2>
<div class="row">
  <div class="col-md-4 category_card">
    <div class="thumbnail">
      <img src="<%= location["logo"]["url"] %>" alt="<%= @location["name"]["text"] %>">
      <div class="caption">
        <p><%= link_to 'Save to Faves', favorites_path(id: location["id"], category: "Event"), {method: :post, class: "btn btn-primary btn-xs"} %></p>
      </div>
    </div>
  </div>
</div> -->

app/views/locations/_yelp_card.html.erb
<!-- <img src="<%= Location.yelp_image_name(location) %>" alt="<%= location.name %>">
<div class="caption">
  <h5><%= "#{category}:" %></h5>
  <h4><%= truncate(location.name, length: 40) %></h4>
  <p><%= Location.address(location) %></p>
  <%= link_to 'Learn More', location_path(id: location.id, category: category), {class: "btn btn-primary btn-xs"} %>
  <%= button_to "Save to Faves", favorites_path(id: location.id, category: category,
                                                name: location.name, image_url: Location.yelp_image_name(location),
                                                address: Location.address(location)),
                                {class: "btn btn-primary btn-xs"}  %>
</div> -->

app/views/locations/_yelp_detail_card.html.erb
<h2><%= @location.name %></h2>
<div class="row">
  <div class="col-md-4 category_card">
    <div class="thumbnail">
      <img src="<%= @location.image_url %>" alt="<%= @location.name %>">
      <div class="caption">
          <p><%= Location.address(@location) %></p>
          <%= button_to "Save to Faves", favorites_path(id: @location.id, category: @category,
                                                        name: @location.name, image_url: @location.image_url,
                                                        address: Location.address(@location)),
                                        {class: "btn btn-primary btn-xs"}  %>
      </div>
    </div>
  </div>
</div>

app/views/locations/index.html.erb
<!-- <h2>Search Results</h2>
<div class="row">
  <% @locations.each do |category, location| %>
    <div class="col-md-4 category_card">
      <div class="thumbnail">
        <% if Category.event?(category) %>
          <%= render partial: "event_card", locals: {location: location} %>
        <% else %>
          <%= render partial: "yelp_card", locals: {category: category, location: location} %>
        <% end %>
      </div>
    </div>
  <% end %>
</div> -->

app/views/locations/show.html.erb
<!-- <% if Category.event?(@category) %>
  <%= render partial: "event_detail_card" %>
<% else %>
  <%= render partial: "yelp_detail_card" %>
<% end %> -->

app/views/search/index.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class='row error hide'>
      <h4>You must choose at least one category.</h4>
    </div>
    <div class="row search-form">
      <h1>Let's Get Started....</h1>
      <%= form_tag(locations_path, {method: "get", class: "form-style-8"}) do %>
      <div class="form-group">
        <%= label_tag('address', "What address do you want to be near?") %>
        <%= text_field_tag('address', @address, class: "form-group") %>
      </div>
        <%= label_tag('distance', "How many miles are you willing to travel?") %>
        <%= select_tag "distance", options_for_select(1..25) %><br />
        <%= label_tag('distance', "What are you looking for?") %><br />
        <%=check_box_tag 'location_categories[bars]'%>
        <%= label_tag('location_categories[bars]', "Bars") %><br />
        <%#=check_box_tag 'location_categories[events]'%>
        <%#= label_tag('location_categories[events]', "Events") %>
        <%=check_box_tag 'location_categories[hotels]'%>
        <%= label_tag('location_categories[hotels]', "Hotels") %><br />
        <%=check_box_tag 'location_categories[museums]'%>
        <%= label_tag('location_categories[museums]', "Museums") %><br />
        <%=check_box_tag 'location_categories[restaurants]'%>
        <%= label_tag('location_categories[restaurants]', "Restaurants") %><br />
        <%= submit_tag "Find Your Night", {:id=>"find-your-night", :class=>"btn btn-danger"} %>
      <% end %>
    </div>
    <div class="row search-results hide">
      <h1>May We Suggest...</h1>
      <div id="spin-again">
      </div>
      <div id="results">
      </div>
    </div>
  </div>
</div>

<div class="modal"></div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="row">
    <div class="col-md-4">
      <h5>About</h5>
      <p>About Mary Jane</p>
    </div>
    <div class="col-md-4">
      <h5>Discover</h5>
      <p>...</p>
    </div>
    <div class="col-md-4">
      <h5>For Business Owners</h5>
      <p>Claim Your Business</p>
    </div>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
<!-- <div class="container-fluid"> -->
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">
      <img src="<%= image_path('logo.png') %>" alt="Mary Jane's Guidebook">
    </a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li>
        <% if current_user %>
          <li><a href="/profile">Your Profile</a></li>
          <li class="divider-vertical"></li>
          <li><a href="/logout">Logout</a></li>
        <% else %>
          <%= link_to "Login", login_path %>
        <% end %></li>
    </ul>
  </div><!-- /.navbar-collapse -->

</nav>

app/views/users/_faves.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default profile">
      <div class="panel-body">
        <h2>Favorites</h2>
        <a href= "/search" class="btn btn-danger">Find More Favorites</a><br /><br />
        <% if @favorites.empty? %>
          <p>You don't have any favorites yet. <a href="/search" >Go find some!</a></p>
        <% else %>
          <% @favorites.each do |location| %>
            <div class="col-md-4 category_card">
              <div class="thumbnail">
                  <%= render partial: "yelp_fave", locals: {category: location.category, location: location} %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_profile_info.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default profile">
      <div class="panel-body">
        <h2>Profile Info</h2>
        <p>Name: <%= current_user.name %></p>
        <p>Username: <%= current_user.screen_name %></p>
      </div>
    </div>
  </div>
</div>

app/views/users/_yelp_fave.html.erb
<img src="<%= location.image_url %>" alt="<%= location.name %>">
<div class="caption">
  <h5><%= location.category %></h5>
  <h4><%= truncate(location.name, length: 40) %></h4>
  <p><%= location.address %></p>
</div>

app/views/users/show.html.erb
<h1><%= current_user.name %>'s Profile</h1>
<%= render partial: "profile_info" %>
<%= render partial: "faves" %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-md-5">
      <img class="intro" src="<%= image_path('your_night.png') %>" alt="City Scape">
    </div>
    <div class="col-md-7">
      <h2>Answering the question "What Should We Do Tonight?"</h2>
      <p>
        <a href= "/search">
          <img class="intro img-responsive" src="<%= image_path('how_it_works.png') %>" alt="How It Works">
        </a>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <img src="<%= image_path('walking.jpg') %>" alt="City Scape">
    </div>
    <div class="col-md-4">
      <img src="<%= image_path('music.jpg') %>" alt="City Scape">
    </div>
    <div class="col-md-4">
      <img src="<%= image_path('skateboard.jpg') %>" alt="City Scape">
    </div>
  </div>
</div>